In [25]:
from sklearn import tree
import numpy as np
import random 
from sklearn.datasets import load_iris
iris= load_iris()
print (iris.feature_names)
print (iris.target_names)
print (iris.data[0])
print (iris.target[0])
#for i in range(len(iris.target)):
    #print ("Example %d: label %s, features %s" % (i, iris.target[i], iris.data[i]))


iris = load_iris()
test_idx = [0, 50, 100]

#training data 
train_target = np.delete(iris.target, test_idx)
train_data= np.delete(iris.data, test_idx, axis=0)

#testing set
test_target = iris.target[test_idx]
test_data = iris.data[test_idx]


clf= tree.DecisionTreeClassifier()
clf.fit(train_data, train_target)

print(test_target)
print(clf.predict(test_data))
print(np.random(3))


['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
[ 5.1  3.5  1.4  0.2]
0
[0 1 2]
[0 1 2]


TypeError: 'module' object is not callable